#ifndef OS_KERNEL_SYSCALL_ABI_H
#define OS_KERNEL_SYSCALL_ABI_H

#include <stdint.h>

enum {
    OS_SYSCALL_DEBUG = 0,
    OS_SYSCALL_WRITE = 1,
    OS_SYSCALL_CLOCK_MONOTONIC = 2,
    OS_SYSCALL_GETPID = 3,
    OS_SYSCALL_SIGNAL_MASK = 4,
    OS_SYSCALL_SIGNAL_SEND = 5,
    OS_SYSCALL_SIGNAL_NEXT = 6,
    OS_SYSCALL_SIGNAL_SEND_TO = 7
};

#define OS_SYSCALL_ERROR UINT64_MAX
#define OS_SYSCALL_MAX_WRITE 256U

#endif
